sitepr/urls.py
from django.urls import include, path
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('votacao/', include('votacao.urls')),
    path('admin/', admin.site.urls),


]
if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

votacao/urls.py
from django.urls import include, path
from . import views





# (. significa que importa views da mesma directoria)

app_name = 'votacao'

urlpatterns = [
 path("", views.index, name="index"),
 path('criaConta', views.criaConta, name='criaConta'),
 path('HomePage', views.HomePage, name='HomePage'),
 path('fazerLogin', views.fazerLogin, name='fazerLogin'),
 path('mostrarFilmes', views.mostrarFilmes, name='mostrarFilmes'),
 path('mostrarSeries', views.mostrarSeries, name='mostrarSeries'),
 path('criarUser', views.criarUserButton, name='criarUserButton'),
 path('administradorPage', views.administradorPage, name='administradorPage'),

 path('criarFilme', views.criarFilme, name='criarFilme'),
path('informacaoPessoal', views.informacaoPessoal,name='informacaoPessoal'),

path('loginview', views.loginview,name='loginview'),
path('logoutview', views.logoutview, name='logoutview'),
path('mudarImagemPerfil', views.mudarImagemPerfil, name='mudarImagemPerfil'),
path('myList', views.myList, name='myList'),
path('pesquisaGeneroFilme', views.pesquisaGeneroFilme, name='pesquisaGeneroFilme'),
path('<int:filme_id>', views.filmePage, name='filmePage'),
path('teste', views.teste,name='teste'),

path('<int:filme_id>/apagarFilmeOuSerie', views.apagarFilmeOuSerie, name='apagarFilmeOuSerie'),

path('pesquisaGeneroSerie', views.pesquisaGeneroSerie, name='pesquisaGeneroSerie'),

path('<int:filme_id>/criarComentario', views.criarComentario, name='criarComentario'),

path('<int:filme_id>/addTolist', views.addTolist, name='addTolist'),

path('<int:filme_id>/delTolist', views.delTolist, name='delTolist'),

path('pesquisa', views.pesquisa, name='pesquisa'),
]

votacao/models.py
from django.db import models
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User




from django.db import models
from django.utils import timezone
from six import string_types
import datetime

# Create your models here.

class Genero(models.Model):
    genero=models.CharField(max_length=100)

    def __str__(self):
        return self.genero

class Subgenero(models.Model):
    genero = models.CharField(max_length=100)

    def __str__(self):
        return self.genero

class Subgenero2(models.Model):
    genero = models.CharField(max_length=100)
    def __str__(self):
        return self.genero


class Filme_ou_serie(models.Model):
    filme_texto = models.CharField(max_length=200) #nome
    filme_ranking_critica = models.IntegerField(default=0)
    genero_id = models.ForeignKey(Genero,on_delete=models.CASCADE,default=0)
    subgenero_id = models.ForeignKey(Subgenero, on_delete=models.CASCADE,default=0)
    subgenero2_id = models.ForeignKey(Subgenero2, on_delete=models.CASCADE,default=0)
    filme_descricao = models.CharField(max_length=3000)
    is_filme = models.IntegerField(default=0) # se estiver a 1 é um filme se estiver a 0 é uma série
    imagem = models.CharField(max_length=300, default='0000000')
    release_year = models.IntegerField(default=0)
    pub_data = models.DateTimeField('data de publicacao')
    trailer = models.CharField(max_length=3000,default=0)
    atores = models.CharField(max_length=3000, default=0)

    def __str__(self):
        return self.filme_texto

    def foi_publicada_recentemente(self):
        return self.pub_data >= timezone.now() -datetime.timedelta(days=15)

class Comentario(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    identificador_conteudo = models.ForeignKey(Filme_ou_serie, on_delete=models.CASCADE)
    comentario_texto = models.CharField(max_length=1500)
    rating = models.IntegerField(default=0) # 0-100
    pub_data = models.DateTimeField('data de publicacao')

    def __str__(self):
        return self.comentario_texto

    def foi_publicada_recentemente_comentario(self):
        return self.pub_data >= timezone.now() -datetime.timedelta(days=15)


class Critico(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    marca = models.CharField(max_length=100)
    imagem = models.CharField(max_length=300, default='0000000')


class WatchList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    identificador_conteudo = models.ForeignKey(Filme_ou_serie, on_delete=models.CASCADE)
    like= models.IntegerField(default=0)

votacao/views.py
# Create your views here.

from .models import Filme_ou_serie, Genero, Comentario, Critico, Subgenero, WatchList, Subgenero2

from django.utils import timezone
from django.db.models import Sum

from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponse,HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.contrib.auth import authenticate, login

from django.contrib.auth.models import User
from django.contrib.auth import logout

from django.conf import settings
from django.core.files.storage import FileSystemStorage

from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required


from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.admin.views.decorators import staff_member_required



def index(request):
   # latest_question_list =Filme_ou_serie.objects.order_by('-pub_data')[:5]
   # context = {'latest_question_list':latest_question_list}
   return render(request, 'votacao/HomePage.html')



def fazerLogin(request):
    return render(request, 'votacao/fazerLogin.html')





def criarUserButton(request):
    uploaded_file_url=''

    filepath = request.FILES.get('myfile', False)
    if request.method == 'POST' and filepath:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)



    email = request.POST['email']
    username = request.POST['username']
    password = request.POST['psw']
    imagem=uploaded_file_url

    if User.objects.filter(username=username).exists():
        return HttpResponseRedirect(reverse('votacao:criaConta'))



    omeuuser = User.objects.create_user(username,email,password)
    ut = Critico(user=omeuuser,imagem=imagem)
    omeuuser.save()
    ut.save()
    user = authenticate(username=username, password=password)
    login(request, user)


    return HttpResponseRedirect(reverse('votacao:HomePage'))



def loginview(request):
 username = request.POST['username']
 password = request.POST['psw']
 user = authenticate(username=username,
 password=password)




 if user is not None:
    login(request, user)
    if user.is_staff==1:
        return HttpResponseRedirect(reverse('votacao:HomePage'))
    #paginaSucesso
    return HttpResponseRedirect(reverse('votacao:HomePage'))
 else:
    # paginaInsucesso(request)
     #paginaInsucesso
     return HttpResponseRedirect(reverse('votacao:fazerLogin'))


@login_required(login_url='/votacao/HomePage')
def informacaoPessoal(request):
    return render(request, 'votacao/informacaoPessoal.html')


@login_required(login_url='/votacao/HomePage')
def mudarImagemPerfil(request):
    current_user = request.user

    filepath = request.FILES.get('myfile', False)
    if request.method == 'POST' and filepath:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        Critico.objects.filter(user_id=current_user.id).update(imagem=uploaded_file_url)
    return render(request, 'votacao/informacaoPessoal.html')





def criaConta(request):
    return render(request, 'votacao/criaConta.html')

def mostrarSeries(request):
    latest_movies_list = Filme_ou_serie.objects.filter(is_filme = 0).order_by('-pub_data')[:5]
    best_movies_list = Filme_ou_serie.objects.filter(is_filme = 0).order_by('-filme_ranking_critica')[:5]
    teste = 0
    context = {'latest_movies_list':latest_movies_list, 'teste':teste, 'best_movies_list':best_movies_list}
    return render(request, 'votacao/mostrarSeries.html',context)


def mostrarFilmes(request):
    latest_movies_list = Filme_ou_serie.objects.filter(is_filme = 1).order_by('-pub_data')[:5]
    best_movies_list = Filme_ou_serie.objects.filter(is_filme = 1).order_by('-filme_ranking_critica')[:5]
    teste = 1
    context = {'latest_movies_list':latest_movies_list, 'teste':teste, 'best_movies_list':best_movies_list}
    return render(request, 'votacao/mostrarFilmes.html',context)

@login_required(login_url='/votacao/HomePage')
def myList(request):
    latest_movies_list = WatchList.objects.filter(user = request.user)[:5]
    teste = 2
    context = {'latest_movies_list':latest_movies_list, 'teste':teste}
    return render(request, 'votacao/myList.html',context)



def HomePage(request):
    best_movies_list = Filme_ou_serie.objects.order_by('-filme_ranking_critica')[:5]
    latest_movies_list = Filme_ou_serie.objects.order_by('-pub_data')[:5]
    context = {'latest_movies_list': latest_movies_list,'best_movies_list':best_movies_list }
    return render(request, 'votacao/HomePage.html', context)

@login_required(login_url='/votacao/HomePage')
def administradorPage(request):
    return render(request, 'votacao/administradorPage.html')



@staff_member_required
def criarFilme(request):
    imagem=''

    filepath = request.FILES.get('myfile', False)
    if request.method == 'POST' and filepath:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        imagem = uploaded_file_url

    if request.method == 'POST' :

        # se a invocação veio do form, isto é, está no 2º passo

        filme_texto = request.POST['nome_filme']
        genero = request.POST['genero']
        subgenero= request.POST['subgenero']
        subgenero2 = request.POST['subgenero2']
        filme_descricao = request.POST['filme_descricao']
        is_filme = request.POST['is_filme']
        anoLancamento= request.POST['anoLancamento']
        trailer = request.POST['trailer']
        atores= request.POST['atores']

        if filme_texto:
            # se a questao_texto está preenchida,
            # então vai instanciar a Questão e depois volta ao detalhe
            generoObject=Genero.objects.get(pk=genero)
            generoObject1 = Subgenero.objects.get(pk=subgenero)
            generoObject2 = Subgenero2.objects.get(pk=subgenero2)
            filme = Filme_ou_serie(filme_texto = filme_texto, filme_ranking_critica = 0, filme_descricao = filme_descricao,is_filme = is_filme, pub_data=timezone.now(), genero_id = generoObject ,release_year = anoLancamento, imagem = imagem,  subgenero2_id = generoObject2, subgenero_id = generoObject1 , trailer = trailer, atores=atores)
            filme.save()
            return HttpResponseRedirect(reverse('votacao:HomePage'))
        else:
            # se a questao_texto não está preenchida, volta ao form
            return HttpResponseRedirect(reverse('votacao:HomePage'))
    else:
         # se a invocação não veio do form, isto é, o 1º passo
        return render(request,'votacao/criarFilme.html')

@login_required(login_url='/votacao/HomePage')
def criarComentario(request, filme_id):
    filme = get_object_or_404(Filme_ou_serie, pk=filme_id)

    if request.method == 'POST' :

        # se a invocação veio do form, isto é, está no 2º passo

        comentario_texto = request.POST['comentario_texto']

        rating = request.POST.get('rating', 0);
        print("rating",rating)
        #rating = request.POST['rating']
        latest_coments_movie_list = Comentario.objects.filter(identificador_conteudo=filme_id)
        latest_movies_list = latest_coments_movie_list.order_by('-pub_data')[:5]
        context = {'latest_movies_list': latest_movies_list, 'filme': filme}

        if comentario_texto and rating != 0:
            # se a questao_texto está preenchida,
            # então vai instanciar a Questão e depois volta ao detalhe
            print("user id ",request.user)
            comentario = Comentario(user= request.user, identificador_conteudo = filme, comentario_texto = comentario_texto, rating = rating, pub_data=timezone.now())
            comentario.save()

            comentarios = Comentario.objects.filter(identificador_conteudo=filme_id)

            nfilmes = comentarios.count()

            totalRating = Comentario.objects.filter(identificador_conteudo=filme_id).aggregate(Sum('rating'))

            totalR = totalRating['rating__sum']
            score = int((totalR / nfilmes)*10)

            print("nfilmes", nfilmes, "totalRating", totalRating, "totalR", totalR, "score", score)
            Filme_ou_serie.objects.filter(pk=filme_id).update(filme_ranking_critica=score)

            return HttpResponseRedirect(reverse('votacao:filmePage',args=(filme_id,)))
        else:
   # se a questao_texto não está preenchida, volta ao form
            return HttpResponseRedirect(reverse('votacao:filmePage',args=(filme_id,)))
    else:
         # se a invocação não veio do form, isto é, o 1º passo
        return HttpResponseRedirect(reverse('votacao:filmePage',args=(filme_id,)))


@login_required(login_url='/votacao/HomePage')
def logoutview(request):
    logout(request)
    return HttpResponseRedirect(reverse('votacao:HomePage'))



def pesquisaGeneroFilme(request):
    #latest_movies_list = Filme_ou_serie.objects.filter(is_filme=filme_id)
    genero=request.POST.get('genero')
    genero=int(genero)

    latest_movies_list1 = Filme_ou_serie.objects.filter(is_filme=1, genero_id=genero).order_by('-pub_data')[:5]
    latest_movies_list2 = Filme_ou_serie.objects.filter(is_filme=1, subgenero_id=genero).order_by('-pub_data')[:5]
    latest_movies_list3 = Filme_ou_serie.objects.filter(is_filme=1, subgenero2_id=genero).order_by('-pub_data')[:5]
    latest_movies_list = (latest_movies_list1 | latest_movies_list2 | latest_movies_list3).order_by('-pub_data')[:5]


    if genero==90:
        latest_movies_list = Filme_ou_serie.objects.filter(filme_ranking_critica__gte=genero).order_by('-pub_data')[:5]
        context = {'latest_movies_list': latest_movies_list,'genero': genero}
        return render(request, 'votacao/pesquisa.html', context)
    if genero == 70:

votacao/templates/votacao/HomePage.html
    <!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      {% block titulo %}
    <title>Home</title>
      {% endblock%}
    <link rel="stylesheet" type="text/css" href="{% static 'votacao/style.css' %}" />
      <link  href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&family=Sen:wght@400;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">



<link rel="icon" href="https://cdn.pixabay.com/photo/2016/02/23/17/29/banana-1218133_1280.png">

  </head>

  <body>
{% block cabecalho %}
    <header>





<script>
function myFunction() {
   var element = document.body;
   element.classList.toggle("dark-mode");
}
</script>

      <nav >
             <div class="toggle" >
                    <i class="fas fa-moon toggle-icon"></i>
                    <i class="fas fa-sun toggle-icon"></i>
                    <div class="toggle-ball" onclick="myFunction()"></div>
                </div>

          <a class="logo"  href="{% url 'votacao:HomePage' %}">🍌Rotten Banana🍌</a>
        <div class="mobile-menu">
          <div class="line1"></div>
          <div class="line2"></div>
          <div class="line3"></div>
        </div>
        <ul class="nav-list">
            <form action="{% url 'votacao:pesquisa' %}" class="formMenu" role="search" id="form">
              <input class = "inputSearchBar" type="search" id="query" name="q"
               placeholder="Search..."
               aria-label="Search through site content">

              <button class="buttonMenu" type="submit">
                <svg viewBox="0 0 1024 1024"><path class="path1" d="M848.471 928l-263.059-263.059c-48.941 36.706-110.118 55.059-177.412 55.059-171.294 0-312-140.706-312-312s140.706-312 312-312c171.294 0 312 140.706 312 312 0 67.294-24.471 128.471-55.059 177.412l263.059 263.059-79.529 79.529zM189.623 408.078c0 121.364 97.091 218.455 218.455 218.455s218.455-97.091 218.455-218.455c0-121.364-103.159-218.455-218.455-218.455-121.364 0-218.455 97.091-218.455 218.455z"></path></svg>
              </button>
            </form>



            <li><a href="{% url 'votacao:HomePage' %}">Inicio</a>
            <li><a href="{% url 'votacao:mostrarFilmes' %}"> Filmes</a></li>
            <li><a href="{% url 'votacao:mostrarSeries' %}"> Séries</a></li>



            {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                        <li><a href="{% url 'votacao:criarFilme' %}"> Criar Filme/Série </a></li>
                        <li><a href="{% url 'votacao:informacaoPessoal' %}"> {{user.username}}</a></li>
                        <li><a href="{% url 'votacao:logoutview' %}"> LOG OUT</a></li>

                    {% else%}
                        <li><a href="{% url 'votacao:myList' %}"> Minha Lista </a></li>
                        <li><a href="{% url 'votacao:informacaoPessoal' %}"> {{user.username}}</a></li>
                        <li><a href="{% url 'votacao:logoutview' %}"> LOG OUT</a></li>
                    {% endif%}

            {% else%}

                <li><a href="{% url 'votacao:criaConta' %}"> Criar Conta</a></li>
                <li><a href="{% url 'votacao:fazerLogin' %}"> LOG IN</a></li>

            {% endif%}

        </ul>
      </nav>
    </header>

    <main></main>
    <script src="{% static 'votacao/scripts.js' %}"></script>

<script>

const arrows = document.querySelectorAll(".arrow");
const movieLists = document.querySelectorAll(".movie-list");

arrows.forEach((arrow, i) => {
  const itemNumber = movieLists[i].querySelectorAll("img").length;
  let clickCounter = 0;
  arrow.addEventListener("click", () => {
    const ratio = Math.floor(window.innerWidth / 270);
    clickCounter++;
    if (itemNumber - (4 + clickCounter) + (4 - ratio) >= 0) {
      movieLists[i].style.transform = `translateX(${
        movieLists[i].computedStyleMap().get("transform")[0].x.value - 300
      }px)`;
    } else {
      movieLists[i].style.transform = "translateX(0)";
      clickCounter = 0;
    }
  });

  console.log(Math.floor(window.innerWidth / 270));
});

//TOGGLE

const ball = document.querySelector(".toggle-ball");
const items = document.querySelectorAll(
  ".container,.movie-list-title,.navbar-container,.sidebar,.left-menu-icon,.toggle"
);

ball.addEventListener("click", () => {
  items.forEach((item) => {
    item.classList.toggle("active");
  });
  ball.classList.toggle("active");
});

</script>



<script>
class MobileNavbar {
  constructor(mobileMenu, navList, navLinks) {
    this.mobileMenu = document.querySelector(mobileMenu);
    this.navList = document.querySelector(navList);
    this.navLinks = document.querySelectorAll(navLinks);
    this.activeClass = "active";

    this.handleClick = this.handleClick.bind(this);
  }

  animateLinks() {
    this.navLinks.forEach((link, index) => {
      link.style.animation
        ? (link.style.animation = "")
        : (link.style.animation = `navLinkFade 0.5s ease forwards ${
            index / 7 + 0.3
          }s`);
    });
  }

  handleClick() {
    this.navList.classList.toggle(this.activeClass);
    this.mobileMenu.classList.toggle(this.activeClass);
    this.animateLinks();
  }

  addClickEvent() {
    this.mobileMenu.addEventListener("click", this.handleClick);
  }

  init() {
    if (this.mobileMenu) {
      this.addClickEvent();
    }
    return this;
  }
}

const mobileNavbar = new MobileNavbar(
  ".mobile-menu",
  ".nav-list",
  ".nav-list li",
);
mobileNavbar.init();
</script>
{% endblock %}

<div class="center" >

{% block filmes%}
 <br>

     <h1 style="color: #23232e"> Novidades </h1>
    <hr>
     <br>
     <br>

    <div class="slideshow-container" >
        {% if latest_movies_list %}
             {% for filme in latest_movies_list %}
                 <div class="mySlides fade" style="text-align:center">
                    <br>
                     <a href="{% url 'votacao:filmePage' filme.id %}"><img src="{{ filme.imagem }}" height="400" width="250" alt="" & onerror="this.style.display='none'"/><h2 style="color: #23232e"> {{ filme.filme_texto }} </h2></a>

                 </div>
             {% endfor %}
          {% else %}
              <p>Nao ha filmes disponiveis.</p>
        {% endif %}
    </div>


<br>

<div style="text-align:center">
    <span class="dot"></span>
    <span class="dot"></span>
    <span class="dot"></span>
    <span class="dot"></span>
    <span class="dot"></span>

</div>


<script>
let slideIndex = 0;
showSlides();

function showSlides() {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  slideIndex++;
  if (slideIndex > slides.length) {slideIndex = 1}
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  setTimeout(showSlides, 4000); // Change image every 4 seconds
}
</script>

  <br>
      <br>
      <br>

            <h1 style="color: #23232e"> Filmes/Séries Com Melhor Rating </h1>

      <hr>
      <br>
        <br>

      {% if latest_movies_list %}
          <div class="content-container">
            <div class="movie-list-container">
                <div class="movie-list">
                    {% for filme in best_movies_list %}


                                <div class="movie-list-item">
                                    <a href="{% url 'votacao:filmePage' filme.id %}"><img class="movie-list-item-img" src="{{ filme.imagem }}" height="315px" width="200px" alt="" & onerror="this.style.display='none'"/><h2 style="color: #23232e"> {{ filme.filme_texto }} </h2></a>
                                    <hr>
                                    <br>
                                    <br>
                                </div>


                    {% endfor %}
                </div>
            </div>
          </div>
      {% else %}
          <p>Nao ha filmes disponiveis.</p>
      {% endif %}
{% endblock %}

{% block categorias%}
{% endblock %}
{% block filme%}
{% endblock %}
{% block videos %}
{% endblock %}

<br>
<br>
{% block footer %}
<footer style="color: #23232e">
    <nav>
        <h2 style="color: #c7ba50"> Guilherme Carvalho Nº92908</h2>
        <h2 style="color: #c7ba50"> João Bicho Nº92425</h2>
        <h2 style="color: #c7ba50"> Miguel Martins Nº93173 </h2>
    </nav >
</footer>
{% endblock %}
</div>



</body>
</html>

votacao/templates/votacao/criaConta.html
{% load static %}


<link rel="icon" href="https://cdn.pixabay.com/photo/2016/02/23/17/29/banana-1218133_1280.png">


   <title>CriarConta</title>

<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box}

body {background-color: #23232e;}

h1 {
	color: #c7ba50;
}
p {
	color: #c7ba50
}
label {
	color: #c7ba50
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #c7ba50;
  margin-bottom: 25px;
}

/* Set a style for all buttons */
button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Extra styles for the cancel button */

.cancelbtn {

  background-color: #f44336;
}

.signupbtn {

  background-color: #04AA6D;
}
/* Float cancel and signup buttons and add an equal width */
.cancelbtn, .signupbtn {
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  opacity: 0.9;
}

/* Add padding to container elements */
.container {
  padding: 16px;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .signupbtn {
     width: 100%;
  }
}
</style>
<body>




<form action="{% url 'votacao:criarUserButton' %}" enctype="multipart/form-data" method="POST">
  {% csrf_token %}
  <div class="container">
    <h1>Criar conta</h1>
    <p>Por favor, preencha o formulário.</p>
    <hr>


<input type="file" name="myfile">


<br><br>


    <label for="email"><b>Email</b></label>
    <input type="text" id="email" placeholder="Enter Email" name="email" required>


      <label for="username"><b>Username</b></label>
    <input type="text" id="username" placeholder="Enter username" name="username" required>



    <label for="psw"><b>Password</b></label>
    <input type="password" id="psw" placeholder="Introduza Password" name="psw" required>

    <label for="psw-repeat"><b>Repita a Password</b></label>
    <input type="password" id="psw-repeat" placeholder="Repita a Password" name="psw-repeat" required>

    <label>
      <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
    </label>





    <div class="clearfix">
      <input type="submit"   value="Cancel"  class="cancelbtn"  formnovalidate formaction="{% url 'votacao:HomePage' %}">
        <input type="submit"   value="Sign Up" class="signupbtn">
    </div>
  </div>
</form>

</body>

votacao/templates/votacao/index.html
   <body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'votacao/style.css' %}" />




 <div class="logo">
<img src="{% static "votacao/images/iscteLogo.png" %}" width="280"
     height="82">


 </div>
{% block questao %}
    <h1 >Não está logado</h1>


<p >Precisas de estar logado para aceder ás questões.</p>
{% endblock %}

{% block questaoList %}
      {% if latest_question_list %}
      <ul>
         {% for questao in latest_question_list %}
         <li>
         {% block referencia_questao %}
            <a href="">{{ questao.questao_texto }}
         {% endblock %}
            </a>
         </li>
         {% endfor %}
      </ul>
      {% else %}
      <p>Nao ha questoes disponiveis.</p>
      {% endif %}
{% endblock %}









{% block Novaquestao %}
   <a href="">Nova Questao</a>
    -Só pode criar uma questão se estiver logado como administrador
    <br>
{% endblock %}

<br>
<br>

{% block informacaoPessoal %}
{% endblock %}

{% block form %}
<form action="{% url 'votacao:loginview' %}" method="POST">
    {% csrf_token %}
    <h1>Login</h1>
  <label for="fname">Username:</label>
  <input type="text" id="fname" name="fname" ><br>
  <label for="lname">Password:</label>
  <input type="password" id="pwd" name="pwd"><br><br>
  <input type="submit" value="Login">
</form>
{% endblock%}

{% block NovoUtilizador %}
    <a href="{% url 'votacao:criarUser' %}">Registar Novo Utilizador</a>
{% endblock %}


   </body>